### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by xTunio** [Wieku/danser#4]
Stacktrace/log:
``` E:\Biblioteki\Pulpit\danser>danser-0.1.2b.exe -title="Can't Defeat Airman" -tag="2" -cursors="1"
2018/08/19 21:15:10 Checking database...
2018/08/19 21:15:10 Imported 0 new beatmaps.
2018/08/19 21:15:10 Found 613 cached beatmaps. Loading...
2018/08/19 21:15:10 Loaded 613 total.
2018/08/19 21:15:11 GLFW initialized!
2018/08/19 21:15:11 BASS Initialized!
2018/08/19 21:15:11 Loading texture:  assets/textures/hitcircle.png
2018/08/19 21:15:11 Loading texture:  assets/textures/approachcircle.png
2018/08/19 21:15:11 Loading texture:  assets/textures/hitcircle-full.png
2018/08/19 21:15:11 Loading texture:  assets/textures/hitcircleoverlay.png
2018/08/19 21:15:11 Loading texture:  assets/textures/slidergradient.png
2018/08/19 21:15:11 Loading texture:  assets/textures/sliderscorepoint.png
2018/08/19 21:15:11 Loading texture:  assets/textures/sliderball.png
2018/08/19 21:15:11 Loading texture:  assets/textures/cursor.png
2018/08/19 21:15:11 Loading texture:  assets/textures/cursor-top.png
2018/08/19 21:15:11 Loading texture:  assets/textures/cursortrail.png
2018/08/19 21:15:11 Can't Defeat Airman
2018/08/19 21:15:11
2018/08/19 21:15:11 Loading texture:  E:\Program files (x86)\osu!\Songs\\Team Nekokan - Can't Defeat Airman\
2018/08/19 21:15:11 er2
2018/08/19 21:15:11 Loading texture:  assets/textures/logo-medium.png
2018/08/19 21:15:11 <nil>
2018/08/19 21:15:11 Team Nekokan - Can't Defeat Airman.mp3
2018/08/19 21:15:11 2147483694 2147483695
2018/08/19 21:15:12 FPS: 637.0935024559166
2018/08/19 21:15:13 FPS: 655.5552649843759
2018/08/19 21:15:14 FPS: 623.3912769522534
2018/08/19 21:15:15 FPS: 626.7669801447643
2018/08/19 21:15:16 FPS: 625.702891596945
2018/08/19 21:15:17 FPS: 627.6562724220981
2018/08/19 21:15:18 FPS: 620.7707224194874
2018/08/19 21:15:19 FPS: 620.6011405628584
2018/08/19 21:15:20 FPS: 607.4080172672456
panic: runtime error: index out of range

goroutine 12 [running]:
github.com/wieku/danser/audio.PlaySample(0x0, 0x4)
        C:/Users/Wieku/go/src/github.com/wieku/danser/audio/osuaudio.go:29 +0xda
github.com/wieku/danser/beatmap/objects.(*Circle).Update(0xc0421aeb60, 0xe1a, 0xc04242ff78)
        C:/Users/Wieku/go/src/github.com/wieku/danser/beatmap/objects/circle.go:59 +0x4c
github.com/wieku/danser/beatmap.(*BeatMap).Update(0xc0422721a0, 0xe1a)
        C:/Users/Wieku/go/src/github.com/wieku/danser/beatmap/beatmap.go:42 +0x184
github.com/wieku/danser/states.NewPlayer.func2(0xc042068570, 0xc0422ad380)
        C:/Users/Wieku/go/src/github.com/wieku/danser/states/player.go:224 +0xae
created by github.com/wieku/danser/states.NewPlayer
        C:/Users/Wieku/go/src/github.com/wieku/danser/states/player.go:217 +0x15bd
```

**Comment by Wieku** [comment]
Can you send the beatmap here?

**Comment by xTunio** [comment]
[https://osu.ppy.sh/b/165](https://osu.ppy.sh/b/165)
